### ISSUE TITLE
What's the plan?

### ISSUE THREAD

**Issue by Bottersnike** [HTStem/Golad.io#1]
I can help work on this, but I'm curious as to what your plan is.
How do you want to draw the game? P5.JS, Canvas or DOM?

**Comment by JayTheYggdrasil** [comment]
I was planning on using the native Canvas and google firebase because I don't know what I'm doing with a server and I don't feel like setting one up. My method could be open to potential board state manipulation though I'm working on a structure that may reduce that ability. It probably would be easier with a server though.

**Comment by Bottersnike** [comment]
Okay. I've whipped together something using the canvas, so I'll merge that quickly

**Comment by Bottersnike** [comment]
Make sure to use the `gh-pages` branch not the `master` branch so that github will host the files for us.
